version: "3"

services:
  web_dev:
    container_name: web_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

volumes:
  node_modules: